# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

pool:
  vmImage: ubuntu-latest

variables:
  - group: docker-settings

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: "2.6.2"
      addToPath: true
    displayName: Use Ruby 2.6.2

  - script: docker-compose -f docker-compose.test.yml build
    displayName: Build test Docker image
  - script: docker-compose -f docker-compose.test.yml run --rm web bundle exec rake
    displayName: Run tests on Docker via rake default

  - script: |
      git reset --hard
      git clean -xdf
    displayName: Clean repository

  - publish: $(System.DefaultWorkingDirectory)
    artifact: repository
    displayName: Publish repository as artifact

  - script:
      docker build --file=Dockerfile --tag=$(dockerRegistry)/$(dockerImageName):$(Build.BuildNumber) --target=web .
    displayName: Build web Docker image

  - script: docker login -u $(dockerId) -p $pass
    env:
      pass: $(dockerPassword)
    displayName: Login to DockerHub
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  - script: |
      docker tag $(dockerRegistry)/$(dockerImageName):$(Build.BuildNumber) $(dockerRegistry)/$(dockerImageName):latest
      docker push $(dockerRegistry)/$(dockerImageName):$(Build.BuildNumber)
      docker push $(dockerRegistry)/$(dockerImageName):latest
    displayName: Push web Docker image
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
