version: "3.7"
services:
  web:
    image: dfedigital/teacher-payments-service:${dockerImageTag}
    restart: on-failure
    ports:
      - "80:3000"

  worker:
    image: dfedigital/teacher-payments-service:${dockerImageTag}
    restart: on-failure
    command: rake jobs:work
